//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_2_BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boletos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boletos()
        {
            this.Transacciones = new HashSet<Transacciones>();
        }
    
        public int NumBoleto { get; set; }
        public int IdFila { get; set; }
        public int IdPresentacion { get; set; }
        public int IdPrecioXBloque { get; set; }
        public int NumAsiento { get; set; }
    
        public virtual Filas Filas { get; set; }
        public virtual Precio_X_Bloque Precio_X_Bloque { get; set; }
        public virtual Presentaciones Presentaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacciones> Transacciones { get; set; }
    }
}
