//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_2_BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precio_X_Bloque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Precio_X_Bloque()
        {
            this.Boletos = new HashSet<Boletos>();
        }
    
        public int IdPrecioXBloque { get; set; }
        public decimal Precio { get; set; }
        public int IdProduccion { get; set; }
        public int IdBloque { get; set; }
    
        public virtual Bloques Bloques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boletos> Boletos { get; set; }
        public virtual Producciones Producciones { get; set; }
    }
}
