//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_2_BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producciones()
        {
            this.Precio_X_Bloque = new HashSet<Precio_X_Bloque>();
            this.Presentaciones = new HashSet<Presentaciones>();
        }
    
        public int IdProduccion { get; set; }
        public string Descripcion { get; set; }
        public string NombrePresentacion { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public int IdTeatro { get; set; }
        public int IdTipoProd { get; set; }
        public string img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Precio_X_Bloque> Precio_X_Bloque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presentaciones> Presentaciones { get; set; }
        public virtual Teatros Teatros { get; set; }
        public virtual Tipos_Produccion Tipos_Produccion { get; set; }
    }
}
