//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_2_BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones
    {
        public int NumFactura { get; set; }
        public string Nombre { get; set; }
        public int Telefono { get; set; }
        public string Mail { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string TipoTransaccion { get; set; }
        public int NumAprobacion { get; set; }
        public int NumBoleto { get; set; }
    
        public virtual Boletos Boletos { get; set; }
    }
}
